export const fixtures = {
"mod": {
  "id": 1676614,
  "module_key": "HSSTATSCO",
  "title": "Client Status",
  "visible": 1,
  "image": "/modules/hsstatsco/media/hsstatsco.png",
  "description": "This module provides an overview of the importance of body measurements and vital signs. Students learn about body measurements for adults and infants and methods and equipment for taking and recording temperature, pulse, respiration, and blood pressure.",
  "old_test_format": 0,
  "showtest": 1,
  "alert": null,
  "future": 0,
  "version": null,
  "resource_break_out": 0,
  "combined_resource_headings": true
},
"unit": {
  "id": 51403,
  "unit_key": "HSSTATSCOEX",
  "title": "Explore",
  "description": "In this activity, students use and care for electronic thermometers with sheaths, tympanic thermometers with probe covers, stethoscopes, sphygmomanometers, scales with height bars and alcohol wipes.",
  "showquiz": 0,
  "quiz_type": 1,
  "future": 0,
  "quiz_question_count": 0,
  "test_question_count": 0,
  "dead": 0,
  "hours": 1.0,
  "teacher_only": 1,
  "curriculum_phase": "EXPLORE"
},
"lesson": {
  "id": 209602,
  "page_set_type": "SCRIPT",
  "unit_key": "HSSTATSCO01",
  "page_set_key": "U_HSSTATSCO01_L01",
  "title": "Vital Signs",
  "sequence": 1,
  "page_count": 7,
  "page_set_extra": null,
  "transfer_files": null,
  "preview_url": "#"
},
"pages":
[
    {
                      "id": 1535307,
             "page_set_id": 209602,
                "unit_key": "HSSTATSCO01",
            "page_set_key": "U_HSSTATSCO01_L01",
                "page_key": "U_HSSTATSCO01_L01_1",
             "page_number": 1,
                  "layout": "5050R-P",
            "page_heading": "What You'll Learn",
               "page_text": "<p>After you finish this lesson, you will be able to:</p>\n<ul class=\"aes-list-b1\">\n<li>Identify the four vital signs.</li>\n<li>Discuss how vital signs can be the first indicators of disease or abnormality.</li>\n<li><div id=\"showme_paragraph_1\">Explain the importance of taking and recording vital signs accurately.</div>\n<!-- Preparing to Entering Sublist -->\n</ul>\n",
              "page_image": "/units/hsstatsco01/media/l01-vitalsigns-p01-01.jpg",
              "page_audio": "/units/hsstatsco01/media/l01-vitalsigns-p01-01.wma",
              "page_video": null,
              "page_extra": null,
                "alt_text": null
    },
    {
                      "id": 1535308,
             "page_set_id": 209602,
                "unit_key": "HSSTATSCO01",
            "page_set_key": "U_HSSTATSCO01_L01",
                "page_key": "U_HSSTATSCO01_L01_2",
             "page_number": 2,
                  "layout": "5050R-P",
            "page_heading": "Vital Signs",
               "page_text": "<p><B>Vital signs </B>are the most important indicators of the health of the body. There are four vital signs. They include temperature, pulse, respiration, and blood pressure.</p>\n<p><div id=\"showme_paragraph_1\">It is critical that vital signs are measured and recorded accurately. These measurements are often the first indication of disease or abnormality.</div></p>\n",
              "page_image": "/units/hsstatsco01/media/ls.hs.status.vitalsigns-p01-01.jpg",
              "page_audio": "/units/hsstatsco01/media/ls.hs.status.vitalsigns-p01-01.wma",
              "page_video": null,
              "page_extra": null,
                "alt_text": null
    },
    {
                      "id": 1535309,
             "page_set_id": 209602,
                "unit_key": "HSSTATSCO01",
            "page_set_key": "U_HSSTATSCO01_L01",
                "page_key": "U_HSSTATSCO01_L01_3",
             "page_number": 3,
                  "layout": "5050R-P",
            "page_heading": "Other Health Indicators",
               "page_text": "<p><div id=\"showme_paragraph_1\">In addition to the four <a class=\"glossary-link\" href=\"javascript:showGlossaryWord('HS_VITAL SIGN');\">vital signs</a>, other indicators of the health of the body can be assessed. Degree of pain felt by a patient is also a good indicator of health. Other indicators include the color of the skin, size of the <a class=\"glossary-link\" href=\"javascript:showGlossaryWord('HS_PUPIL');\">pupils</a>, reaction of the pupils to light, level of consciousness, and the patient's reaction to <a class=\"glossary-link\" href=\"javascript:showGlossaryWord('HS_STIMULI');\">stimuli</a>.</div></p>\n",
              "page_image": "/units/hsstatsco01/media/ls.hs.status.vitalsigns-p02-01.jpg",
              "page_audio": "/units/hsstatsco01/media/ls.hs.status.vitalsigns-p02-01.wma",
              "page_video": null,
              "page_extra": null,
                "alt_text": null
    },
    {
                      "id": 1535310,
             "page_set_id": 209602,
                "unit_key": "HSSTATSCO01",
            "page_set_key": "U_HSSTATSCO01_L01",
                "page_key": "U_HSSTATSCO01_L01_4",
             "page_number": 4,
                  "layout": "QUESTIONS",
            "page_heading": "Check Your Understanding",
               "page_text": "",
              "page_image": null,
              "page_audio": null,
              "page_video": null,
              "page_extra": null,
                "alt_text": null
    },
    {
                      "id": 1535311,
             "page_set_id": 209602,
                "unit_key": "HSSTATSCO01",
            "page_set_key": "U_HSSTATSCO01_L01",
                "page_key": "U_HSSTATSCO01_L01_5",
             "page_number": 5,
                  "layout": "DRAGDROP",
            "page_heading": "Vital Signs Exercise",
               "page_text": "<p>Place the items in the correct category.</p>\n<ol class=\"aes-list-number\">\n<li value=\"1\">Click an item and hold down the mouse button.</li>\n<li value=\"2\">Drag the item to the correct location.</li>\n<li value=\"3\">Release the mouse button.</li>\n<li value=\"4\">To start over, click <B>Reset Exercise </B>in the box below.\n<!-- Preparing to Entering Sublist -->\n</ol>\n",
              "page_image": null,
              "page_audio": null,
              "page_video": null,
              "page_extra": "<DRAGDROP_PRESENTATION tag=\"@CATEGORIZETEXT\" params=\"Basic\"><property name=\"@DART\" value=\"YES,NO,NO,LESSONQUIZ=NO,UNITTEST=NO,COURSEEXAM=NO\"/><property name=\"@LIBRARYSOURCE\" value=\"LS.HS.Status.VitalSigns\"/><property name=\"KEY\" value=\"@CATEGORIZETEXT_1LS.HS.Status.VitalSigns\"/><DRAGDROP_PARAMETER tag=\"@DNDBACKGROUND\" params=\"sort2categories.png\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DNDTITLE\" params=\"A~Vital Signs\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DNDTITLE\" params=\"B~Other Indicators\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DND\" params=\"A~Temperature\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DND\" params=\"A~Pulse\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DND\" params=\"A~Respiration\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DND\" params=\"A~Blood Pressure\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DND\" params=\"B~Pain\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DND\" params=\"B~Skin Color\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DND\" params=\"B~Pupil Size\"></DRAGDROP_PARAMETER><DRAGDROP_PARAMETER tag=\"@DND\" params=\"B~Reaction to Stimuli\"></DRAGDROP_PARAMETER></DRAGDROP_PRESENTATION>",
                "alt_text": null
    },
    {
                      "id": 1535312,
             "page_set_id": 209602,
                "unit_key": "HSSTATSCO01",
            "page_set_key": "U_HSSTATSCO01_L01",
                "page_key": "U_HSSTATSCO01_L01_6",
             "page_number": 6,
                  "layout": "5050R-P",
            "page_heading": "Lesson Summary",
               "page_text": "<p>In this lesson, you learned about vital signs and other signs of the health of the body.</p>\n<p>In this lesson, you learned that:</p>\n<ul class=\"aes-list-b1\">\n<li>The four vital signs are temperature, pulse, respiration, and blood pressure.</li>\n<li>Vital signs can be the first indicators of disease or abnormality.</li>\n<li><div id=\"showme_paragraph_1\">It is critical to take and record vital signs accurately.</div>\n<!-- Preparing to Entering Sublist -->\n</ul>\n",
              "page_image": "/units/hsstatsco01/media/l01-vitalsigns-p01-01.jpg",
              "page_audio": "/units/hsstatsco01/media/l01-vitalsigns-p02-01.wma",
              "page_video": null,
              "page_extra": null,
                "alt_text": null
    },
    {
                      "id": 1535313,
             "page_set_id": 209602,
                "unit_key": "HSSTATSCO01",
            "page_set_key": "U_HSSTATSCO01_L01",
                "page_key": "U_HSSTATSCO01_L01_7",
             "page_number": 7,
                  "layout": "5050R-I",
            "page_heading": "Exit the Lesson",
               "page_text": "<ol class=\"aes-list-number\">\n<li value=\"1\">If you would like to continue working, click <B>Home </B>and go on to the next lesson in this unit.</li>\n<li value=\"2\"><div id=\"showme_paragraph_1\">If you are finished working, click <B>Log Off </B>to exit the class.</div>\n<!-- Preparing to Entering Sublist -->\n</ol>\n",
              "page_image": "/units/hsstatsco01/media/ls.hs.standard.lesson.finish.notlast.aa-01-01.jpg",
              "page_audio": null,
              "page_video": null,
              "page_extra": null,
                "alt_text": null
    }
]

};

